# ── MacroPad9 · Pro Micro NRF52840 genérico ──────────────────────
# Habilitar USB (cable) y Bluetooth simultáneamente
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Sleep automático a los 15 minutos de inactividad (en ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
